module.exports = [
  {
    file: "free-summer-programs-high-school.html",
    title: "Free Summer Programs for High School Students",
    description: "A ranked list of free or funded summer programs that are actually worth a high-school student's attention, with notes on selectivity, fit, and timing.",
    audience: "High-school students trying to find real summer options without paying thousands just to look busy.",
    whyThisPage: "This page is for students who want summer options that build actual skill, research exposure, leadership, or community impact. The list favors fully free programs first, then funded or aid-friendly options that still make sense for students without private-program budgets.",
    query: "free summer programs for high school students",
    bestBetsIntro: "If you only have time to go deep on three options, start with one realistic stretch, one strong fit, and one lower-friction builder.",
    bestBets: ["Girls Who Code Pathways", "Summer Science Program", "Yale Young Global Scholars"],
    entries: [
      { title: "Girls Who Code Pathways", note: "One of the best low-cost ways to come out of a summer with a project, community, and something real to show.", goodFor: "Students who want a free, remote, beginner-friendly way to build a project.", skipIf: "You need a research-heavy or math-heavy program.", reachMatchSafety: "match" },
      { title: "MIT Beaver Works Summer Institute", note: "Excellent if you want a serious technical summer and can handle a fast pace.", goodFor: "Students who already like coding, engineering, or building systems.", skipIf: "You want something casual or exploratory.", reachMatchSafety: "reach" },
      { title: "Summer Science Program", note: "A strong bet if you want to be immersed in STEM all summer and are ready for real intensity.", goodFor: "Students with solid science or math preparation.", skipIf: "You are still figuring out whether you even like STEM work day to day.", reachMatchSafety: "reach" },
      { title: "Yale Young Global Scholars", note: "Not fully free, but one of the better-known funded options if you can access aid.", goodFor: "Students who want a broad academic or leadership summer with strong peers.", skipIf: "You need a guaranteed no-cost option.", reachMatchSafety: "match" },
      { title: "COSMOS", note: "Worth serious attention if you are in California and want strong STEM cluster options without private-program pricing.", goodFor: "Students who want real academic structure and lab-adjacent work.", skipIf: "Travel or state eligibility makes it unrealistic.", reachMatchSafety: "match" },
      { title: "Boston University RISE", note: "Useful if you want research-style structure, but it is not the first option I would chase without funding.", goodFor: "Students who want formal lab or internship tracks.", skipIf: "Cost is a hard barrier.", reachMatchSafety: "reach" },
      { title: "Simons Summer Research Program", note: "A serious research-facing option with real upside if you are ready for selective science work.", goodFor: "Students who already have evidence of STEM depth.", skipIf: "You are still at the 'I might like research' stage.", reachMatchSafety: "reach" },
      { title: "George Mason ASSIP", note: "A very good example of a program that feels more useful than flashy if you want applied research exposure.", goodFor: "Students who want mentored science or engineering work.", skipIf: "You are not ready to communicate sustained interest clearly.", reachMatchSafety: "match" },
      { title: "Texas Tech Clark Scholars", note: "Prestigious and tiny. Worth applying to if you already have strong evidence, but not your only plan.", goodFor: "Students with strong academics and a clear project or research narrative.", skipIf: "You need a likely outcome more than a dream application.", reachMatchSafety: "reach" },
      { title: "TASS", note: "A standout if you care about reading, writing, argument, and social analysis more than generic enrichment.", goodFor: "Students who want serious humanities work in the summer.", skipIf: "You only want a STEM-facing page on your resume.", reachMatchSafety: "match" },
      { title: "NSLI-Y", note: "One of the most meaningful options here if language and cultural immersion actually interest you.", goodFor: "Students who want a language path with real depth and public meaning.", skipIf: "You are applying just because it sounds prestigious.", reachMatchSafety: "match" },
      { title: "SAMS at Carnegie Mellon", note: "Strong for students interested in rigorous STEM preparation and access pathways.", goodFor: "Students looking for a structured, high-support summer around STEM readiness.", skipIf: "You want a loose or self-directed summer.", reachMatchSafety: "match" },
      { title: "LEDA Scholars", note: "A strong move if your bigger goal is long-term college access and support, not just one summer line item.", goodFor: "Students who want support, advising, and access-building.", skipIf: "You only want a technical program.", reachMatchSafety: "match" },
      { title: "Notre Dame Leadership Seminars", note: "Useful if you want writing, discussion, and leadership signal rather than another generic pre-college course.", goodFor: "Students with strong communication and discussion interests.", skipIf: "You are looking for research or lab work.", reachMatchSafety: "match" }
    ]
  },
  {
    file: "scholarships-for-juniors-and-seniors.html",
    title: "Scholarships for Juniors and Seniors",
    description: "A ranked scholarship guide that favors realistic, reputable, student-worth-it opportunities over random scholarship spam.",
    audience: "High-school juniors and seniors trying to spend effort on scholarships that are actually worth the time.",
    whyThisPage: "Most students do not need more scholarship search engines. They need a cleaner shortlist and honest notes about which scholarships are worth the essay, which are too selective to anchor a plan around, and which ones are useful early for habit-building.",
    query: "scholarships for juniors seniors first gen need based merit",
    bestBetsIntro: "These are the first three I would explain to a student who wants to be strategic instead of drowning in low-quality scholarship lists.",
    bestBets: ["QuestBridge College Prep Scholars", "Dell Scholars", "College Board BigFuture Scholarships"],
    entries: [
      { title: "QuestBridge College Prep Scholars", note: "One of the best early signals for high-achieving, low-income students because it builds momentum before senior year.", goodFor: "Juniors who want structure, visibility, and college-access support.", skipIf: "You do not match the financial context it is built for.", reachMatchSafety: "match" },
      { title: "Dell Scholars", note: "Worth real attention because it is not just about grades; it looks for persistence and context.", goodFor: "Students with strong resilience stories and real college-going need.", skipIf: "You are looking for a low-effort, no-context application.", reachMatchSafety: "match" },
      { title: "College Board BigFuture Scholarships", note: "Not life-changing alone, but a smart early habit-builder for younger students who need to start somewhere.", goodFor: "Students in 9th-11th grade who need a low-friction way to start planning.", skipIf: "You only want highly selective named awards.", reachMatchSafety: "safety" },
      { title: "QuestBridge National College Match", note: "Massive upside, but it asks for real preparation. Treat it like a major application project, not a casual add-on.", goodFor: "Strong seniors who fit the financial and academic profile.", skipIf: "You cannot devote serious time to the application.", reachMatchSafety: "reach" },
      { title: "Gates Scholarship", note: "Excellent if it fits you, but too selective to be your only plan.", goodFor: "High-achieving Pell-eligible students with strong leadership and academic evidence.", skipIf: "You need a dependable scholarship strategy, not a moonshot only.", reachMatchSafety: "reach" },
      { title: "Horatio Alger Scholarships", note: "A better fit than many students realize if adversity is actually part of the story and documented honestly.", goodFor: "Students with significant hardship context.", skipIf: "Your application would feel generic or thin.", reachMatchSafety: "match" },
      { title: "Ron Brown Scholar Program", note: "Prestigious and demanding, but meaningful if your leadership and service work are already real.", goodFor: "Students with a strong academic and community leadership record.", skipIf: "You would be forcing the service story.", reachMatchSafety: "reach" },
      { title: "Hispanic Scholarship Fund", note: "One of the more straightforward reputable options for eligible students and worth keeping on the list.", goodFor: "Eligible students who want a known national organization rather than random listings.", skipIf: "You do not meet the identity or eligibility requirements.", reachMatchSafety: "match" },
      { title: "Jackie Robinson Foundation Scholarship", note: "A serious opportunity with strong support, but not something to rush through.", goodFor: "Students ready to present academics, leadership, and service clearly.", skipIf: "You cannot give the application real time.", reachMatchSafety: "reach" },
      { title: "Amazon Future Engineer Scholarship", note: "A good targeted option if your computing interest is already visible in your record.", goodFor: "Students with a credible CS or engineering trajectory.", skipIf: "You are trying to backfill a technical story at the last second.", reachMatchSafety: "match" },
      { title: "Coca-Cola Scholars Program", note: "Huge name recognition, but also huge competition. Apply if your leadership is already strong, not because the brand is famous.", goodFor: "Students with broad school or community leadership evidence.", skipIf: "You need likely returns for your application time.", reachMatchSafety: "reach" },
      { title: "Jack Kent Cooke College Scholarship", note: "A major prize if you fit, but you still need a broader scholarship plan around it.", goodFor: "High-performing students with strong academic records and financial need.", skipIf: "You are treating it like a standalone safety net.", reachMatchSafety: "reach" },
      { title: "Elks Most Valuable Student", note: "A solid classic scholarship to keep in rotation if you have time for one more reputable national application.", goodFor: "Students who want a known national scholarship without spammy framing.", skipIf: "You are already overloaded with stronger-fit essays.", reachMatchSafety: "match" },
      { title: "Scholarship America Student Resources", note: "Better as a vetted starting point than a destination. Use it to find programs, not to replace judgment.", goodFor: "Students who need a cleaner scholarship entry point.", skipIf: "You already have a strong shortlist and do not need another search layer.", reachMatchSafety: "safety" }
    ]
  },
  {
    file: "cybersecurity-competitions-for-students.html",
    title: "Cybersecurity Competitions for Students",
    description: "A practical cybersecurity guide for students who want beginner-to-intermediate routes through competitions, courses, and public proof.",
    audience: "Students interested in cyber, systems, and hands-on technical skill who need a route that starts before internships become realistic.",
    whyThisPage: "Students interested in cybersecurity often need a path, not just one flashy competition. This guide mixes competitions, builders, and low-friction training options so you can move from curiosity to visible proof.",
    query: "cyber cybersecurity cyberpatriot ctf netacad",
    bestBetsIntro: "These three together create a better starting loop than hunting for prestige too early.",
    bestBets: ["picoCTF", "CyberPatriot", "IBM SkillsBuild"],
    entries: [
      { title: "picoCTF", note: "Probably the best starting point here for students who want to learn by doing instead of reading about cyber forever.", goodFor: "Beginners who want approachable challenges and visible progress.", skipIf: "You need a team-based structure to stay engaged.", reachMatchSafety: "safety" },
      { title: "CyberPatriot", note: "Excellent for students who want teamwork, season structure, and proof they can work under constraints.", goodFor: "Students who can find or build a team and want a serious competition loop.", skipIf: "You only want solo learning.", reachMatchSafety: "match" },
      { title: "IBM SkillsBuild", note: "One of the cleaner free platforms for building job-adjacent cyber and tech skills without gatekeeping.", goodFor: "Students who need accessible self-paced training.", skipIf: "You only care about competition signal.", reachMatchSafety: "safety" },
      { title: "National Cyber League", note: "A good next step once you want a more serious challenge than beginner CTFs.", goodFor: "Students who already like solving practical security tasks.", skipIf: "You are still brand-new to command-line work.", reachMatchSafety: "match" },
      { title: "Congressional App Challenge", note: "Not cyber-specific, but still useful if your security interest shows up through the product you build.", goodFor: "Students who want a public project outcome and demo.", skipIf: "You want security work more than general app-building.", reachMatchSafety: "match" },
      { title: "Technovation Girls", note: "A strong community-minded builder route if you want code, problem-solving, and a project you can explain.", goodFor: "Students who want mission-driven technical work.", skipIf: "You only want pure security challenge environments.", reachMatchSafety: "match" },
      { title: "USA Computing Olympiad", note: "More algorithms than cyber, but still useful if you want stronger technical depth.", goodFor: "Students who enjoy harder problem solving and want sharper fundamentals.", skipIf: "You are looking for applied systems work specifically.", reachMatchSafety: "reach" },
      { title: "AWS Educate", note: "Good support material if you want infrastructure vocabulary and platform familiarity.", goodFor: "Students building cloud or systems context alongside cyber.", skipIf: "You need game-like practice to stay motivated.", reachMatchSafety: "safety" },
      { title: "Microsoft Learn Student Hub", note: "Useful as a free training layer when you need direction between competitions.", goodFor: "Students who want guided modules and product-adjacent skills.", skipIf: "You are already consistent with another training platform.", reachMatchSafety: "safety" },
      { title: "Girls Who Code Clubs", note: "Not cyber-specific, but still valuable if you need a place to build leadership, consistency, and technical community.", goodFor: "Students who need structure and peer accountability.", skipIf: "You already have a stronger local technical community.", reachMatchSafety: "match" },
      { title: "Google Code Next", note: "A strong broader computing opportunity if you want mentorship and technical growth around underrepresented access.", goodFor: "Students who want computing depth with community and support.", skipIf: "You are looking only for direct cyber branding.", reachMatchSafety: "reach" },
      { title: "Major League Hacking Events", note: "Hackathons are not cyber competitions, but they are still useful for project reps and technical confidence.", goodFor: "Students who need deadlines and teammates to actually build.", skipIf: "You want a security-specific proving ground.", reachMatchSafety: "match" }
    ]
  },
  {
    file: "engineering-open-houses-and-campus-visits.html",
    title: "Engineering Open Houses and Campus Visits",
    description: "A ranked guide to engineering visits and open houses that help students understand what programs actually feel like before applying.",
    audience: "Students trying to decide where engineering fits them and what different campuses actually offer beyond brochure language.",
    whyThisPage: "Campus visits are useful when they help you inspect the real environment: labs, project spaces, student teams, advising, and how engineering is taught. This list favors visits that are especially useful for engineering-minded students rather than generic walking tours alone.",
    query: "engineering open house campus tour visit",
    bestBetsIntro: "If you can only visit a few places or events, prioritize the ones that show the most real engineering activity, not just admissions theater.",
    bestBets: ["UIUC Engineering Open House", "Purdue AAE Prospective Family Visits", "Purdue Campus Visits"],
    entries: [
      { title: "UIUC Engineering Open House", note: "One of the clearest examples of a visit that shows engineering culture instead of just talking about it.", goodFor: "Students who want to see projects, teams, and lab energy in person.", skipIf: "Travel makes it unrealistic this cycle.", reachMatchSafety: "match" },
      { title: "Purdue AAE Prospective Family Visits", note: "Especially strong if aerospace or a highly specific engineering direction is already on your mind.", goodFor: "Students interested in aerospace or wanting a closer academic look than a general tour.", skipIf: "You still need broad campus context first.", reachMatchSafety: "match" },
      { title: "Purdue Campus Visits", note: "A practical starting point because it gives broader context before you decide whether a more specialized visit is worth the trip.", goodFor: "Students beginning the campus-comparison stage.", skipIf: "You already know the school and need only department depth.", reachMatchSafety: "safety" },
      { title: "UIUC College Open Houses", note: "Useful when you want structured exposure to a big engineering environment without guessing what to ask.", goodFor: "Students comparing several engineering-adjacent colleges or majors.", skipIf: "You need department-specific detail more than overview.", reachMatchSafety: "match" },
      { title: "MIT Admissions Visit", note: "Worth doing if available, but use it to inspect culture and pace rather than chasing brand aura.", goodFor: "Students who want to pressure-test whether an intense technical environment feels energizing or draining.", skipIf: "You are going only for prestige sightseeing.", reachMatchSafety: "reach" },
      { title: "Stanford Campus Visit", note: "A good visit for vibe and ecosystem context, but you still need to ask hard questions about day-to-day engineering life.", goodFor: "Students curious about entrepreneurship plus engineering culture.", skipIf: "You need the visit itself to answer specific departmental questions.", reachMatchSafety: "reach" },
      { title: "Georgia Tech Visit", note: "A useful benchmark school if you want to compare strong engineering identity and campus feel.", goodFor: "Students comparing highly technical campuses.", skipIf: "Travel cost outweighs the clarity you would gain.", reachMatchSafety: "match" },
      { title: "UC Berkeley Visitor Services", note: "Helpful if you want ecosystem exposure, though you may need extra work to get engineering-specific detail.", goodFor: "Students exploring large public STEM environments.", skipIf: "You expect the general visit to answer all major-specific questions.", reachMatchSafety: "match" },
      { title: "Carnegie Mellon Admission Visits", note: "Worth it if you are drawn to rigorous technical culture and want to test whether it feels right.", goodFor: "Students who care about program intensity and focus.", skipIf: "You want a relaxed broad-campus first stop.", reachMatchSafety: "reach" },
      { title: "University of Michigan Visit", note: "A strong comparison point if you want a big-campus engineering experience with lots happening.", goodFor: "Students evaluating large public engineering ecosystems.", skipIf: "You need a smaller or more intimate environment.", reachMatchSafety: "match" },
      { title: "Cornell Visit", note: "Useful if you want to compare a strong engineering school in a more distinct physical setting.", goodFor: "Students who care about program strength and environment equally.", skipIf: "Travel makes this mostly aspirational right now.", reachMatchSafety: "reach" },
      { title: "Harvard Visit", note: "Good for context, but not the first engineering-specific trip I would recommend if you need major clarity.", goodFor: "Students comparing elite campuses broadly.", skipIf: "You need direct engineering signal more than general brand context.", reachMatchSafety: "reach" }
    ]
  },
  {
    file: "free-college-credit-and-fee-waivers.html",
    title: "Free College Credit and Fee Waiver Resources",
    description: "A practical affordability guide for students trying to lower application, testing, and college-planning costs while building momentum early.",
    audience: "Students and families who need lower-cost pathways, better planning, and fewer wasted application dollars.",
    whyThisPage: "Affordability work starts earlier than many students think. This page mixes fee waivers, planning tools, and lower-cost credit pathways so you can cut waste before senior panic hits.",
    query: "fee waiver act sat college credit dual enrollment",
    bestBetsIntro: "If cost is your biggest constraint, start with the resources that reduce friction before you chase selective scholarships.",
    bestBets: ["FAFSA", "BigFuture", "QuestBridge College Prep Scholars"],
    entries: [
      { title: "FAFSA", note: "Not optional if affordability matters. Even students who think they will not qualify often need to understand it earlier.", goodFor: "Students and families preparing for financial-aid reality.", skipIf: "You want scholarship-only thinking instead of the full affordability picture.", reachMatchSafety: "safety" },
      { title: "BigFuture", note: "A solid planning layer that is actually useful when treated like a tool instead of a marketing funnel.", goodFor: "Students starting a college-cost and search workflow.", skipIf: "You already have a strong planning system.", reachMatchSafety: "safety" },
      { title: "QuestBridge College Prep Scholars", note: "One of the most meaningful early affordability moves if you fit the context.", goodFor: "Juniors who want access support before senior year.", skipIf: "You do not match the financial profile it is built around.", reachMatchSafety: "match" },
      { title: "College Scorecard", note: "A better reality check than vibes when you need to compare actual outcomes and cost.", goodFor: "Students trying to compare colleges without fantasy pricing.", skipIf: "You are still at the stage of pure inspiration, not comparison.", reachMatchSafety: "safety" },
      { title: "RaiseMe", note: "Worth exploring if your schools still honor it, but verify how current and useful it is for your targets.", goodFor: "Students who want early feedback on college-going milestones.", skipIf: "You assume every micro-scholarship model is equally active everywhere.", reachMatchSafety: "match" },
      { title: "Common App", note: "Not a fee-waiver answer by itself, but central if you want to understand application logistics before deadline season gets messy.", goodFor: "Students preparing for multi-school application workflows.", skipIf: "You need funding answers more than application logistics right now.", reachMatchSafety: "safety" },
      { title: "Coalition Scoir Application", note: "Useful to know, especially if specific schools you care about use it heavily.", goodFor: "Students comparing application systems.", skipIf: "Your likely school list leans Common App anyway.", reachMatchSafety: "safety" },
      { title: "College Board BigFuture Scholarships", note: "Low-friction enough that younger students should not ignore it just because it is not glamorous.", goodFor: "Students building early planning habits.", skipIf: "You already have limited bandwidth and stronger direct applications to finish.", reachMatchSafety: "safety" },
      { title: "Scholarship America Student Resources", note: "Helpful as a reputable starting map when random scholarship search results feel sketchy.", goodFor: "Students who need a cleaner scholarship entry point.", skipIf: "You already know exactly which awards you are pursuing.", reachMatchSafety: "match" },
      { title: "OpenStax", note: "Not a fee waiver, but an immediate way to reduce academic-material costs and study more independently.", goodFor: "Students trying to save money while learning core coursework well.", skipIf: "You need application logistics more than study support.", reachMatchSafety: "safety" },
      { title: "Google Applied Digital Skills", note: "A good lower-friction builder if you want free skill growth before paying for another pre-college experience.", goodFor: "Students who need skill-building without cost.", skipIf: "You are already committed to a deeper technical track elsewhere.", reachMatchSafety: "safety" },
      { title: "CollegePoint", note: "A good support resource if you need advising-like help without paying for private counseling.", goodFor: "Students who want cost-conscious guidance and college-planning support.", skipIf: "You already have strong local counselor support.", reachMatchSafety: "match" }
    ]
  },
  {
    file: "writing-history-humanities-resources.html",
    title: "Writing, History, and Humanities Resources",
    description: "A humanities guide for students who want stronger writing, reading, research, and argument without STEM-only tunnel vision.",
    audience: "Students building evidence through writing, history, languages, philosophy, and research rather than only STEM signals.",
    whyThisPage: "Humanities students usually get worse recommendation lists than STEM students. This page focuses on tools, courses, competitions, and research-facing resources that help you produce better writing and clearer thinking.",
    query: "writing history humanities research essay language",
    bestBetsIntro: "If you want a smaller, stronger starting stack, begin with one writing tool, one reading/research source, and one visible output opportunity.",
    bestBets: ["Purdue OWL", "National History Day", "Open Yale Courses"],
    entries: [
      { title: "Purdue OWL", note: "Still one of the best practical writing references because it helps you fix the work in front of you.", goodFor: "Students writing essays, scholarship responses, or research papers.", skipIf: "You need deep subject content more than writing support.", reachMatchSafety: "safety" },
      { title: "National History Day", note: "A genuinely useful way to turn history interest into a visible project instead of just another class grade.", goodFor: "Students who want research, argument, and presentation evidence.", skipIf: "You do not want project work with deadlines.", reachMatchSafety: "match" },
      { title: "Open Yale Courses", note: "A strong free layer if you want serious humanities content without paying for pre-college gloss.", goodFor: "Students ready to self-direct their reading and note-taking.", skipIf: "You need structure more than content.", reachMatchSafety: "match" },
      { title: "Yale Online", note: "Good as a broad free academic source when you want to sample serious topics without committing money.", goodFor: "Students exploring subjects before choosing a direction.", skipIf: "You already know exactly what narrower topic you need.", reachMatchSafety: "safety" },
      { title: "Khan Academy AP US History", note: "Underrated if you need foundations before you can do stronger independent work.", goodFor: "Students who want free structure around historical knowledge.", skipIf: "You already need primary-source depth more than course review.", reachMatchSafety: "safety" },
      { title: "Library of Congress Research Guides", note: "A real upgrade once you want better primary-source and research pathways than a normal web search gives you.", goodFor: "Students doing projects, papers, or source-based work.", skipIf: "You are still struggling to define the question itself.", reachMatchSafety: "match" },
      { title: "Stanford Encyclopedia of Philosophy", note: "Excellent if you want substance, but use it as part of a note-taking process instead of passive browsing.", goodFor: "Students interested in philosophy, ethics, or sharper conceptual thinking.", skipIf: "You want lighter introductory reading.", reachMatchSafety: "match" },
      { title: "Zotero", note: "One of the best upgrades for longer writing or research because it makes your sources stop living in chaos.", goodFor: "Students doing multi-source writing or research.", skipIf: "Your assignments are still too short to justify the setup.", reachMatchSafety: "match" },
      { title: "Mendeley Reference Manager", note: "A useful alternative citation workflow, especially if you are juggling PDFs and notes.", goodFor: "Students growing into longer-form research management.", skipIf: "Zotero already works for you.", reachMatchSafety: "safety" },
      { title: "Grammarly for Students", note: "Helpful for cleanup, but not a substitute for thinking. Use it after the argument is yours.", goodFor: "Students who need help with clarity and proofreading.", skipIf: "You are using it to avoid learning revision.", reachMatchSafety: "safety" },
      { title: "Obsidian", note: "Great if your notes need to outlive one assignment and turn into a system.", goodFor: "Students doing long-running writing, reading, or research projects.", skipIf: "You want the lightest possible notes setup.", reachMatchSafety: "match" },
      { title: "Duolingo", note: "Not enough by itself for language depth, but excellent for keeping the habit alive every day.", goodFor: "Students building consistency in a language path.", skipIf: "You expect it to replace real reading, listening, or classwork.", reachMatchSafety: "safety" }
    ]
  }
];
